### ISSUE TITLE
llvm-profdata required for processing profiles

### ISSUE THREAD

**Issue by alphan** [lowRISC/lowrisc-toolchains#31]
I am currently working on collecting coverage data from the target and we need `llvm-profdata` to index raw profiles.

It would be great if it could be included in the toolchain.

@lenary @luismarques

**Comment by lenary** [comment]
I think llvm-cov is in the toolchain, looking at it now, but we can certainly add `llvm-profdata`.

**Comment by alphan** [comment]
> I think llvm-cov is in the toolchain, looking at it now, but we can certainly add `llvm-profdata`.

You're right, sorry, I guess I only looked for `llvm-profdata` because that's what I needed first and forgot to check `llvm-cov`.
